### ISSUE TITLE
Cannot connect Bloomberg Data License via RblDataLicense

### ISSUE THREAD

**Issue by thitiphong7805** [eguidotti/RblDataLicense#1]
Hi 
I used Rblconnect . Then, it showed up like this
"Authentication failure: check your credentials and whitelist the IP address in use. Contact Bloomberg support for help.[1] FALSE"

How can I fix this problem

**Comment by eguidotti** [comment]
Hi,
Please note that as a prerequisite, a valid Data License from Bloomberg is needed together with the corresponding SFTP credentials and whitelisting of the IP from which accessing the service. 

The credentials consist of the username and password needed by `RblConnect(user, pw)`. 
As an additional security measure, all requests are blocked by default by Bloomberg and are only accepted if coming from a whitelisted IP address. You need to inform Bloomberg of the IP addresses you are using to access the service. Only correctly authenticated requests from whitelisted IP will work. Contact Bloomberg support for whitelisting.

The `RblDataLicense` is a lightweight package built on top of the [RCurl](https://cran.r-project.org/package=RCurl), a wrapper for [libcurl](https://curl.haxx.se/libcurl/). The package establishes sftp connections to Bloomberg Datalicense. On some Linux systems, this may not work out of the box, as libcurl does not natively support sftp. If you are in that case, you should compile curl with SFTP support first.
