### ISSUE TITLE
Outdated connection defaults? 

### ISSUE THREAD

**Issue by ojessen** [eguidotti/RblDataLicense#4]
Hi,
I'm not sure if this is a general issue, but the default values for the sftp server seem to have changed. What works for me now is 

`res_connect = RblConnect(user = bl_user, pw = bl_pw, host = "sftp.bloomberg.com", port = 22)`

Best regards,
Owe

**Comment by eguidotti** [comment]
Hi @ojessen and thanks for your message.
Unfortunately it is not possible for me to check this is a general issue. I'll leave it open for a while so that if other users report the same issue I'll update the default parameters.

Best,
Emanuele

**Comment by michaelbolger** [comment]
Hi @eguidotti,

I also came across this issue. dlsftp... continues to work for us in some places, but sftp.bloomberg.com seems to be the recommended host (see [here](https://service.blpprofessional.com/track_download/assets/data-license/#10-3-4-ip-addresses)).

Kind regards,

Michael

**Comment by eguidotti** [comment]
Thanks @michaelbolger for confirming this.
I have updated the default parameters to `host = "sftp.bloomberg.com"` and `port = "22"`.
The new release v0.2.4 should fix this. This new version should be available on CRAN in a couple of days.

Many thanks,
Emanuele
