### ISSUE TITLE
Authentication Failure Issue

### ISSUE THREAD

**Issue by roharagit** [eguidotti/RblDataLicense#5]
Good afternoon. I'm trying to connect to Bloomberg (I'm Using  Bloomberg Anywhere via Citrix) using R software (RblDataLicence package) and I'm getting the following error:
Authentication failure: check your configurations and whitelist the IP address in use. Contact Bloomberg support for help.[1] FALSE
 
Here is how I'm trying to connect:
RblConnect(user = "roh...", 
 pw = "....",
host = "dlsftp.bloomberg.com",
port = "30206",
protocol = "sftp",
verbose = TRUE
)

Thank you,
Rich O'Hara

**Comment by eguidotti** [comment]
Hello @roharagit, thanks for opening an issue here. I have nothing to do with Bloomberg but it seems to me that Bloomberg Anywhere allows access to the Bloomberg Terminal, not to the Bloomberg Data License. Do you have a valid Bloomberg Data License subscription? If instead you are trying to access the Terminal the right package should be [Rblpapi](https://cran.r-project.org/web/packages/Rblpapi/index.html) but I don't know how it works remotely. Hope this helps!
