### ISSUE TITLE
Requesting monthly data

### ISSUE THREAD

**Issue by jessgoltara** [eguidotti/RblDataLicense#6]
Hi, 
I'm trying to request monthly data but I'm not sure about which function should I use and what is the parameter to establish that. Thank you for your time.

**Comment by eguidotti** [comment]
Hi @jessgoltara, I'm afraid there is no parameter for the frequency of the data in the package. Only daily data work out of the box.
You may want to build a custom query for that using [RblRequestBuilder](https://rbldatalicense.guidotti.dev/reference/RblRequestBuilder.html)
Hope that works!
